spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casino_bot
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
